import pyttsx3
import pytz
from datetime import datetime
import speech_recognition as sr
import paho.mqtt.client as mqtt

# Your MQTT broker settings
MQTT_BROKER_HOST = "broker.emqx.io"  # Replace with your MQTT broker's hostname or IP
MQTT_BROKER_PORT = 1883  # Default MQTT port
MQTT_TOPIC = "alarm_system"  # MQTT topic to publish messages

# Dictionary of country names and their corresponding timezones
country_timezones = {
    "USA": ["America/New_York", "America/Los_Angeles"],
    "UK": ["Europe/London"],
    "Japan": ["Asia/Tokyo"],
    "Canada": ["America/Toronto", "America/Vancouver"],
    "Australia": ["Australia/Sydney", "Australia/Melbourne"],
    "Germany": ["Europe/Berlin"],
    "France": ["Europe/Paris"],
    "Italy": ["Europe/Rome"],
    "Spain": ["Europe/Madrid"],
    "Netherlands": ["Europe/Amsterdam"],
    "Sweden": ["Europe/Stockholm"],
    "Switzerland": ["Europe/Zurich"],
    "Belgium": ["Europe/Brussels"],
    "Norway": ["Europe/Oslo"],
    "Denmark": ["Europe/Copenhagen"],
    "Finland": ["Europe/Helsinki"],
    "Russia": ["Europe/Moscow", "Asia/Krasnoyarsk", "Asia/Yekaterinburg"],
    "China": ["Asia/Shanghai", "Asia/Chongqing"],
    "India": ["Asia/Kolkata"],
    "Brazil": ["America/Sao_Paulo"],
    "Mexico": ["America/Mexico_City"],
    "Argentina": ["America/Argentina/Buenos_Aires"],
    "Chile": ["America/Santiago"],
    "Peru": ["America/Lima"],
    "Colombia": ["America/Bogota"],
    "Venezuela": ["America/Caracas"],
    "South Africa": ["Africa/Johannesburg"],
    "Egypt": ["Africa/Cairo"],
    "Nigeria": ["Africa/Lagos"],
    "Kenya": ["Africa/Nairobi"],
    "Ghana": ["Africa/Accra"],
    "Morocco": ["Africa/Casablanca"],
    "Saudi Arabia": ["Asia/Riyadh"],
    "United Arab Emirates": ["Asia/Dubai"],
    "Turkey": ["Europe/Istanbul"],
    "Pakistan": ["Asia/Karachi"],
    "Bangladesh": ["Asia/Dhaka"],
    "Indonesia": ["Asia/Jakarta"],
    "Thailand": ["Asia/Bangkok"],
    "Vietnam": ["Asia/Ho_Chi_Minh"],
    "South Korea": ["Asia/Seoul"],
    "Philippines": ["Asia/Manila"],
    "Malaysia": ["Asia/Kuala_Lumpur"],
    "Singapore": ["Asia/Singapore"],
    "New Zealand": ["Pacific/Auckland"],
    "Fiji": ["Pacific/Fiji"],
    "Austria": ["Europe/Vienna"],
    "Greece": ["Europe/Athens"],
    "Portugal": ["Europe/Lisbon"],
    "Poland": ["Europe/Warsaw"],
    "Hungary": ["Europe/Budapest"],
    "Czech Republic": ["Europe/Prague"],
    "Slovakia": ["Europe/Bratislava"],
    "Romania": ["Europe/Bucharest"],
    "Bulgaria": ["Europe/Sofia"],
    "Ukraine": ["Europe/Kiev"],
    "Belarus": ["Europe/Minsk"],
    "Estonia": ["Europe/Tallinn"],
    "Latvia": ["Europe/Riga"],
    "Lithuania": ["Europe/Vilnius"],
    "Croatia": ["Europe/Zagreb"],
    "Slovenia": ["Europe/Ljubljana"],
    "Bosnia and Herzegovina": ["Europe/Sarajevo"],
    "Serbia": ["Europe/Belgrade"],
    "Montenegro": ["Europe/Podgorica"],
    "Albania": ["Europe/Tirane"],
    "North Macedonia": ["Europe/Skopje"],
    "Kosovo": ["Europe/Belgrade"],
    "Moldova": ["Europe/Chisinau"],
    "Georgia": ["Asia/Tbilisi"],
    "Armenia": ["Asia/Yerevan"],
    "Azerbaijan": ["Asia/Baku"],
    "Kazakhstan": ["Asia/Almaty", "Asia/Aqtau"],
    "Kyrgyzstan": ["Asia/Bishkek"],
    "Tajikistan": ["Asia/Dushanbe"],
    "Turkmenistan": ["Asia/Ashgabat"],
    "Uzbekistan": ["Asia/Tashkent"],
    "Iran": ["Asia/Tehran"],
    "Iraq": ["Asia/Baghdad"],
    "Afghanistan": ["Asia/Kabul"],
    "Syria": ["Asia/Damascus"],
    "Lebanon": ["Asia/Beirut"],
    "Jordan": ["Asia/Amman"],
    "Israel": ["Asia/Jerusalem"],
    "Palestine": ["Asia/Gaza", "Asia/Hebron"],
    "Qatar": ["Asia/Qatar"],
    "Bahrain": ["Asia/Bahrain"],
    "Kuwait": ["Asia/Kuwait"],
    "Oman": ["Asia/Muscat"],
    "Yemen": ["Asia/Aden"],
    "Sri Lanka": ["Asia/Colombo"],
    "Maldives": ["Indian/Maldives"],
    "Nepal": ["Asia/Kathmandu"],
    "Bhutan": ["Asia/Thimphu"],
    "Myanmar": ["Asia/Yangon"],
    "Laos": ["Asia/Vientiane"],
    "Cambodia": ["Asia/Phnom_Penh"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Brunei": ["Asia/Brunei"],
    "Timor-Leste": ["Asia/Dili"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Samoa": ["Pacific/Apia"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Federated States of Micronesia": ["Pacific/Pohnpei"],
    "Mauritius": ["Indian/Mauritius"],
    "Seychelles": ["Indian/Mahe"],
    "Madagascar": ["Indian/Antananarivo"],
    "Comoros": ["Indian/Comoro"],
    "Malawi": ["Africa/Blantyre"],
    "Zimbabwe": ["Africa/Harare"],
    "Zambia": ["Africa/Lusaka"],
    "Namibia": ["Africa/Windhoek"],
    "Botswana": ["Africa/Gaborone"],
    "Lesotho": ["Africa/Maseru"],
    "Eswatini": ["Africa/Mbabane"],
    "Angola": ["Africa/Luanda"],
    "Mozambique": ["Africa/Maputo"],
    "Tanzania": ["Africa/Dar_es_Salaam"],
    "Uganda": ["Africa/Kampala"],
    "Rwanda": ["Africa/Kigali"],
    "Burundi": ["Africa/Bujumbura"],
    "Democratic Republic of the Congo": ["Africa/Kinshasa", "Africa/Lubumbashi"],
    "Republic of the Congo": ["Africa/Brazzaville"],
    "Cameroon": ["Africa/Douala"],
    "Central African Republic": ["Africa/Bangui"],
    "Chad": ["Africa/Ndjamena"],
    "Niger": ["Africa/Niamey"],
    "Benin": ["Africa/Porto-Novo"],
    "Togo": ["Africa/Lome"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Senegal": ["Africa/Dakar"],
    "Mali": ["Africa/Bamako"],
    "Guinea": ["Africa/Conakry"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Sierra Leone": ["Africa/Freetown"],
    "Liberia": ["Africa/Monrovia"],
    "Ivory Coast": ["Africa/Abidjan"],
    "Greece": ["Europe/Athens"],
    "Portugal": ["Europe/Lisbon"],
    "Poland": ["Europe/Warsaw"],
    "Hungary": ["Europe/Budapest"],
    "Czech Republic": ["Europe/Prague"],
    "Slovakia": ["Europe/Bratislava"],
    "Romania": ["Europe/Bucharest"],
    "Bulgaria": ["Europe/Sofia"],
    "Ukraine": ["Europe/Kiev"],
    "Belarus": ["Europe/Minsk"],
    "Estonia": ["Europe/Tallinn"],
    "Latvia": ["Europe/Riga"],
    "Lithuania": ["Europe/Vilnius"],
    "Croatia": ["Europe/Zagreb"],
    "Slovenia": ["Europe/Ljubljana"],
    "Bosnia and Herzegovina": ["Europe/Sarajevo"],
    "Serbia": ["Europe/Belgrade"],
    "Montenegro": ["Europe/Podgorica"],
    "Albania": ["Europe/Tirane"],
    "North Macedonia": ["Europe/Skopje"],
    "Kosovo": ["Europe/Belgrade"],
    "Moldova": ["Europe/Chisinau"],
    "Georgia": ["Asia/Tbilisi"],
    "Armenia": ["Asia/Yerevan"],
    "Azerbaijan": ["Asia/Baku"],
    "Kazakhstan": ["Asia/Almaty", "Asia/Aqtau"],
    "Kyrgyzstan": ["Asia/Bishkek"],
    "Tajikistan": ["Asia/Dushanbe"],
    "Turkmenistan": ["Asia/Ashgabat"],
    "Uzbekistan": ["Asia/Tashkent"],
    "Iran": ["Asia/Tehran"],
    "Iraq": ["Asia/Baghdad"],
    "Afghanistan": ["Asia/Kabul"],
    "Syria": ["Asia/Damascus"],
    "Lebanon": ["Asia/Beirut"],
    "Jordan": ["Asia/Amman"],
    "Israel": ["Asia/Jerusalem"],
    "Palestine": ["Asia/Gaza", "Asia/Hebron"],
    "Qatar": ["Asia/Qatar"],
    "Bahrain": ["Asia/Bahrain"],
    "Kuwait": ["Asia/Kuwait"],
    "Oman": ["Asia/Muscat"],
    "Yemen": ["Asia/Aden"],
    "Sri Lanka": ["Asia/Colombo"],
    "Maldives": ["Indian/Maldives"],
    "Nepal": ["Asia/Kathmandu"],
    "Bhutan": ["Asia/Thimphu"],
    "Myanmar": ["Asia/Yangon"],
    "Laos": ["Asia/Vientiane"],
    "Cambodia": ["Asia/Phnom_Penh"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Brunei": ["Asia/Brunei"],
    "Timor-Leste": ["Asia/Dili"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Samoa": ["Pacific/Apia"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Federated States of Micronesia": ["Pacific/Pohnpei"],
    "Mauritius": ["Indian/Mauritius"],
    "Seychelles": ["Indian/Mahe"],
    "Madagascar": ["Indian/Antananarivo"],
    "Comoros": ["Indian/Comoro"],
    "Malawi": ["Africa/Blantyre"],
    "Zimbabwe": ["Africa/Harare"],
    "Zambia": ["Africa/Lusaka"],
    "Namibia": ["Africa/Windhoek"],
    "Botswana": ["Africa/Gaborone"],
    "Lesotho": ["Africa/Maseru"],
    "Eswatini": ["Africa/Mbabane"],
    "Angola": ["Africa/Luanda"],
    "Mozambique": ["Africa/Maputo"],
    "Tanzania": ["Africa/Dar_es_Salaam"],
    "Uganda": ["Africa/Kampala"],
    "Rwanda": ["Africa/Kigali"],
    "Burundi": ["Africa/Bujumbura"],
    "Democratic Republic of the Congo": ["Africa/Kinshasa", "Africa/Lubumbashi"],
    "Republic of the Congo": ["Africa/Brazzaville"],
    "Cameroon": ["Africa/Douala"],
    "Central African Republic": ["Africa/Bangui"],
    "Chad": ["Africa/Ndjamena"],
    "Niger": ["Africa/Niamey"],
    "Benin": ["Africa/Porto-Novo"],
    "Togo": ["Africa/Lome"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Senegal": ["Africa/Dakar"],
    "Mali": ["Africa/Bamako"],
    "Guinea": ["Africa/Conakry"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Sierra Leone": ["Africa/Freetown"],
    "Liberia": ["Africa/Monrovia"],
    "Ivory Coast": ["Africa/Abidjan"],
    "Mauritania": ["Africa/Nouakchott"],
    "Benin": ["Africa/Porto-Novo"],
    "Eritrea": ["Africa/Asmara"],
    "Eritrea": ["Africa/Asmara"],
    "Somalia": ["Africa/Mogadishu"],
    "Djibouti": ["Africa/Djibouti"],
    "Algeria": ["Africa/Algiers"],
    "Burundi": ["Africa/Bujumbura"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Equatorial Guinea": ["Africa/Malabo"],
    "Swaziland": ["Africa/Mbabane"],
    "Lesotho": ["Africa/Maseru"],
    "Botswana": ["Africa/Gaborone"],
    "Comoros": ["Indian/Comoro"],
    "Cabo Verde": ["Atlantic/Cape_Verde"],
    "Samoa": ["Pacific/Apia"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Tonga": ["Pacific/Tongatapu"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Cook Islands": ["Pacific/Rarotonga"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Palau": ["Pacific/Palau"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Nauru": ["Pacific/Nauru"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tonga": ["Pacific/Tongatapu"],
    "Fiji": ["Pacific/Fiji"],
    "Samoa": ["Pacific/Apia"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Fiji": ["Pacific/Fiji"],
    "Tonga": ["Pacific/Tongatapu"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Fiji": ["Pacific/Fiji"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Malta": ["Europe/Malta"],
    "Cyprus": ["Asia/Nicosia"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Tajikistan": ["Asia/Dushanbe"],
    "Turkmenistan": ["Asia/Ashgabat"],
    "Uzbekistan": ["Asia/Tashkent"],
    "Iran": ["Asia/Tehran"],
    "Iraq": ["Asia/Baghdad"],
    "Afghanistan": ["Asia/Kabul"],
    "Syria": ["Asia/Damascus"],
    "Lebanon": ["Asia/Beirut"],
    "Jordan": ["Asia/Amman"],
    "Israel": ["Asia/Jerusalem"],
    "Palestine": ["Asia/Gaza", "Asia/Hebron"],
    "Qatar": ["Asia/Qatar"],
    "Bahrain": ["Asia/Bahrain"],
    "Kuwait": ["Asia/Kuwait"],
    "Oman": ["Asia/Muscat"],
    "Yemen": ["Asia/Aden"],
    "Sri Lanka": ["Asia/Colombo"],
    "Maldives": ["Indian/Maldives"],
    "Nepal": ["Asia/Kathmandu"],
    "Bhutan": ["Asia/Thimphu"],
    "Myanmar": ["Asia/Yangon"],
    "Laos": ["Asia/Vientiane"],
    "Cambodia": ["Asia/Phnom_Penh"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Brunei": ["Asia/Brunei"],
    "Timor-Leste": ["Asia/Dili"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Samoa": ["Pacific/Apia"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Federated States of Micronesia": ["Pacific/Pohnpei"],
    "Mauritius": ["Indian/Mauritius"],
    "Seychelles": ["Indian/Mahe"],
    "Madagascar": ["Indian/Antananarivo"],
    "Comoros": ["Indian/Comoro"],
    "Malawi": ["Africa/Blantyre"],
    "Zimbabwe": ["Africa/Harare"],
    "Zambia": ["Africa/Lusaka"],
    "Namibia": ["Africa/Windhoek"],
    "Botswana": ["Africa/Gaborone"],
    "Lesotho": ["Africa/Maseru"],
    "Eswatini": ["Africa/Mbabane"],
    "Angola": ["Africa/Luanda"],
    "Mozambique": ["Africa/Maputo"],
    "Tanzania": ["Africa/Dar_es_Salaam"],
    "Uganda": ["Africa/Kampala"],
    "Rwanda": ["Africa/Kigali"],
    "Burundi": ["Africa/Bujumbura"],
    "Democratic Republic of the Congo": ["Africa/Kinshasa", "Africa/Lubumbashi"],
    "Republic of the Congo": ["Africa/Brazzaville"],
    "Cameroon": ["Africa/Douala"],
    "Central African Republic": ["Africa/Bangui"],
    "Chad": ["Africa/Ndjamena"],
    "Niger": ["Africa/Niamey"],
    "Benin": ["Africa/Porto-Novo"],
    "Togo": ["Africa/Lome"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Senegal": ["Africa/Dakar"],
    "Mali": ["Africa/Bamako"],
    "Guinea": ["Africa/Conakry"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Sierra Leone": ["Africa/Freetown"],
    "Liberia": ["Africa/Monrovia"],
    "Ivory Coast": ["Africa/Abidjan"],
    "Mauritania": ["Africa/Nouakchott"],
    "Benin": ["Africa/Porto-Novo"],
    "Eritrea": ["Africa/Asmara"],
    "Somalia": ["Africa/Mogadishu"],
    "Djibouti": ["Africa/Djibouti"],
    "Algeria": ["Africa/Algiers"],
    "Burundi": ["Africa/Bujumbura"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Equatorial Guinea": ["Africa/Malabo"],
    "Swaziland": ["Africa/Mbabane"],
    "Lesotho": ["Africa/Maseru"],
    "Botswana": ["Africa/Gaborone"],
    "Comoros": ["Indian/Comoro"],
    "Cabo Verde": ["Atlantic/Cape_Verde"],
    "Samoa": ["Pacific/Apia"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Tonga": ["Pacific/Tongatapu"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Cook Islands": ["Pacific/Rarotonga"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Palau": ["Pacific/Palau"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Nauru": ["Pacific/Nauru"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tonga": ["Pacific/Tongatapu"],
    "Fiji": ["Pacific/Fiji"],
    "Samoa": ["Pacific/Apia"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Fiji": ["Pacific/Fiji"],
    "Tonga": ["Pacific/Tongatapu"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Fiji": ["Pacific/Fiji"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Malta": ["Europe/Malta"],
    "Cyprus": ["Asia/Nicosia"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Tajikistan": ["Asia/Dushanbe"],
    "Turkmenistan": ["Asia/Ashgabat"],
    "Uzbekistan": ["Asia/Tashkent"],
    "Iran": ["Asia/Tehran"],
    "Iraq": ["Asia/Baghdad"],
    "Afghanistan": ["Asia/Kabul"],
    "Syria": ["Asia/Damascus"],
    "Lebanon": ["Asia/Beirut"],
    "Jordan": ["Asia/Amman"],
    "Israel": ["Asia/Jerusalem"],
    "Palestine": ["Asia/Gaza", "Asia/Hebron"],
    "Qatar": ["Asia/Qatar"],
    "Bahrain": ["Asia/Bahrain"],
    "Kuwait": ["Asia/Kuwait"],
    "Oman": ["Asia/Muscat"],
    "Yemen": ["Asia/Aden"],
    "Sri Lanka": ["Asia/Colombo"],
    "Maldives": ["Indian/Maldives"],
    "Nepal": ["Asia/Kathmandu"],
    "Bhutan": ["Asia/Thimphu"],
    "Myanmar": ["Asia/Yangon"],
    "Laos": ["Asia/Vientiane"],
    "Cambodia": ["Asia/Phnom_Penh"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Brunei": ["Asia/Brunei"],
    "Timor-Leste": ["Asia/Dili"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Samoa": ["Pacific/Apia"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Federated States of Micronesia": ["Pacific/Pohnpei"],
    "Mauritius": ["Indian/Mauritius"],
    "Seychelles": ["Indian/Mahe"],
    "Madagascar": ["Indian/Antananarivo"],
    "Comoros": ["Indian/Comoro"],
    "Malawi": ["Africa/Blantyre"],
    "Zimbabwe": ["Africa/Harare"],
    "Zambia": ["Africa/Lusaka"],
    "Namibia": ["Africa/Windhoek"],
    "Botswana": ["Africa/Gaborone"],
    "Lesotho": ["Africa/Maseru"],
    "Eswatini": ["Africa/Mbabane"],
    "Angola": ["Africa/Luanda"],
    "Mozambique": ["Africa/Maputo"],
    "Tanzania": ["Africa/Dar_es_Salaam"],
    "Uganda": ["Africa/Kampala"],
    "Rwanda": ["Africa/Kigali"],
    "Burundi": ["Africa/Bujumbura"],
    "Democratic Republic of the Congo": ["Africa/Kinshasa", "Africa/Lubumbashi"],
    "Republic of the Congo": ["Africa/Brazzaville"],
    "Cameroon": ["Africa/Douala"],
    "Central African Republic": ["Africa/Bangui"],
    "Chad": ["Africa/Ndjamena"],
    "Niger": ["Africa/Niamey"],
    "Benin": ["Africa/Porto-Novo"],
    "Togo": ["Africa/Lome"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Senegal": ["Africa/Dakar"],
    "Mali": ["Africa/Bamako"],
    "Guinea": ["Africa/Conakry"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Sierra Leone": ["Africa/Freetown"],
    "Liberia": ["Africa/Monrovia"],
    "Ivory Coast": ["Africa/Abidjan"],
    "Mauritania": ["Africa/Nouakchott"],
    "Benin": ["Africa/Porto-Novo"],
    "Eritrea": ["Africa/Asmara"],
    "Somalia": ["Africa/Mogadishu"],
    "Djibouti": ["Africa/Djibouti"],
    "Algeria": ["Africa/Algiers"],
    "Burundi": ["Africa/Bujumbura"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Equatorial Guinea": ["Africa/Malabo"],
    "Swaziland": ["Africa/Mbabane"],
    "Lesotho": ["Africa/Maseru"],
    "Botswana": ["Africa/Gaborone"],
    "Comoros": ["Indian/Comoro"],
    "Cabo Verde": ["Atlantic/Cape_Verde"],
    "Samoa": ["Pacific/Apia"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Tonga": ["Pacific/Tongatapu"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Cook Islands": ["Pacific/Rarotonga"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Palau": ["Pacific/Palau"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Nauru": ["Pacific/Nauru"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tonga": ["Pacific/Tongatapu"],
    "Fiji": ["Pacific/Fiji"],
    "Samoa": ["Pacific/Apia"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Fiji": ["Pacific/Fiji"],
    "Tonga": ["Pacific/Tongatapu"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Fiji": ["Pacific/Fiji"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Malta": ["Europe/Malta"],
    "Cyprus": ["Asia/Nicosia"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Tajikistan": ["Asia/Dushanbe"],
    "Turkmenistan": ["Asia/Ashgabat"],
    "Uzbekistan": ["Asia/Tashkent"],
    "Iran": ["Asia/Tehran"],
    "Iraq": ["Asia/Baghdad"],
    "Afghanistan": ["Asia/Kabul"],
    "Syria": ["Asia/Damascus"],
    "Lebanon": ["Asia/Beirut"],
    "Jordan": ["Asia/Amman"],
    "Israel": ["Asia/Jerusalem"],
    "Palestine": ["Asia/Gaza", "Asia/Hebron"],
    "Qatar": ["Asia/Qatar"],
    "Bahrain": ["Asia/Bahrain"],
    "Kuwait": ["Asia/Kuwait"],
    "Oman": ["Asia/Muscat"],
    "Yemen": ["Asia/Aden"],
    "Sri Lanka": ["Asia/Colombo"],
    "Maldives": ["Indian/Maldives"],
    "Nepal": ["Asia/Kathmandu"],
    "Bhutan": ["Asia/Thimphu"],
    "Myanmar": ["Asia/Yangon"],
    "Laos": ["Asia/Vientiane"],
    "Cambodia": ["Asia/Phnom_Penh"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Brunei": ["Asia/Brunei"],
    "Timor-Leste": ["Asia/Dili"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Samoa": ["Pacific/Apia"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Federated States of Micronesia": ["Pacific/Pohnpei"],
    "Mauritius": ["Indian/Mauritius"],
    "Seychelles": ["Indian/Mahe"],
    "Madagascar": ["Indian/Antananarivo"],
    "Comoros": ["Indian/Comoro"],
    "Malawi": ["Africa/Blantyre"],
    "Zimbabwe": ["Africa/Harare"],
    "Zambia": ["Africa/Lusaka"],
    "Namibia": ["Africa/Windhoek"],
    "Botswana": ["Africa/Gaborone"],
    "Lesotho": ["Africa/Maseru"],
    "Eswatini": ["Africa/Mbabane"],
    "Angola": ["Africa/Luanda"],
    "Mozambique": ["Africa/Maputo"],
    "Tanzania": ["Africa/Dar_es_Salaam"],
    "Uganda": ["Africa/Kampala"],
    "Rwanda": ["Africa/Kigali"],
    "Burundi": ["Africa/Bujumbura"],
    "Democratic Republic of the Congo": ["Africa/Kinshasa", "Africa/Lubumbashi"],
    "Republic of the Congo": ["Africa/Brazzaville"],
    "Cameroon": ["Africa/Douala"],
    "Central African Republic": ["Africa/Bangui"],
    "Chad": ["Africa/Ndjamena"],
    "Niger": ["Africa/Niamey"],
    "Benin": ["Africa/Porto-Novo"],
    "Togo": ["Africa/Lome"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Senegal": ["Africa/Dakar"],
    "Mali": ["Africa/Bamako"],
    "Guinea": ["Africa/Conakry"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Sierra Leone": ["Africa/Freetown"],
    "Liberia": ["Africa/Monrovia"],
    "Ivory Coast": ["Africa/Abidjan"],
    "Mauritania": ["Africa/Nouakchott"],
    "Benin": ["Africa/Porto-Novo"],
    "Eritrea": ["Africa/Asmara"],
    "Somalia": ["Africa/Mogadishu"],
    "Djibouti": ["Africa/Djibouti"],
    "Algeria": ["Africa/Algiers"],
    "Burundi": ["Africa/Bujumbura"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Equatorial Guinea": ["Africa/Malabo"],
    "Swaziland": ["Africa/Mbabane"],
    "Lesotho": ["Africa/Maseru"],
    "Botswana": ["Africa/Gaborone"],
    "Comoros": ["Indian/Comoro"],
    "Cabo Verde": ["Atlantic/Cape_Verde"],
    "Samoa": ["Pacific/Apia"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Tonga": ["Pacific/Tongatapu"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Cook Islands": ["Pacific/Rarotonga"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Palau": ["Pacific/Palau"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Nauru": ["Pacific/Nauru"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tonga": ["Pacific/Tongatapu"],
    "Fiji": ["Pacific/Fiji"],
    "Samoa": ["Pacific/Apia"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Fiji": ["Pacific/Fiji"],
    "Tonga": ["Pacific/Tongatapu"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Fiji": ["Pacific/Fiji"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Malta": ["Europe/Malta"],
    "Cyprus": ["Asia/Nicosia"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Tajikistan": ["Asia/Dushanbe"],
    "Turkmenistan": ["Asia/Ashgabat"],
    "Uzbekistan": ["Asia/Tashkent"],
    "Iran": ["Asia/Tehran"],
    "Iraq": ["Asia/Baghdad"],
    "Afghanistan": ["Asia/Kabul"],
    "Syria": ["Asia/Damascus"],
    "Lebanon": ["Asia/Beirut"],
    "Jordan": ["Asia/Amman"],
    "Israel": ["Asia/Jerusalem"],
    "Palestine": ["Asia/Gaza", "Asia/Hebron"],
    "Qatar": ["Asia/Qatar"],
    "Bahrain": ["Asia/Bahrain"],
    "Kuwait": ["Asia/Kuwait"],
    "Oman": ["Asia/Muscat"],
    "Yemen": ["Asia/Aden"],
    "Sri Lanka": ["Asia/Colombo"],
    "Maldives": ["Indian/Maldives"],
    "Nepal": ["Asia/Kathmandu"],
    "Bhutan": ["Asia/Thimphu"],
    "Myanmar": ["Asia/Yangon"],
    "Laos": ["Asia/Vientiane"],
    "Cambodia": ["Asia/Phnom_Penh"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Brunei": ["Asia/Brunei"],
    "Timor-Leste": ["Asia/Dili"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Samoa": ["Pacific/Apia"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Federated States of Micronesia": ["Pacific/Pohnpei"],
    "Mauritius": ["Indian/Mauritius"],
    "Seychelles": ["Indian/Mahe"],
    "Madagascar": ["Indian/Antananarivo"],
    "Comoros": ["Indian/Comoro"],
    "Malawi": ["Africa/Blantyre"],
    "Zimbabwe": ["Africa/Harare"],
    "Zambia": ["Africa/Lusaka"],
    "Namibia": ["Africa/Windhoek"],
    "Botswana": ["Africa/Gaborone"],
    "Lesotho": ["Africa/Maseru"],
    "Eswatini": ["Africa/Mbabane"],
    "Angola": ["Africa/Luanda"],
    "Mozambique": ["Africa/Maputo"],
    "Tanzania": ["Africa/Dar_es_Salaam"],
    "Uganda": ["Africa/Kampala"],
    "Rwanda": ["Africa/Kigali"],
    "Burundi": ["Africa/Bujumbura"],
    "Democratic Republic of the Congo": ["Africa/Kinshasa", "Africa/Lubumbashi"],
    "Republic of the Congo": ["Africa/Brazzaville"],
    "Cameroon": ["Africa/Douala"],
    "Central African Republic": ["Africa/Bangui"],
    "Chad": ["Africa/Ndjamena"],
    "Niger": ["Africa/Niamey"],
    "Benin": ["Africa/Porto-Novo"],
    "Togo": ["Africa/Lome"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Senegal": ["Africa/Dakar"],
    "Mali": ["Africa/Bamako"],
    "Guinea": ["Africa/Conakry"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Sierra Leone": ["Africa/Freetown"],
    "Liberia": ["Africa/Monrovia"],
    "Ivory Coast": ["Africa/Abidjan"],
    "Mauritania": ["Africa/Nouakchott"],
    "Benin": ["Africa/Porto-Novo"],
    "Eritrea": ["Africa/Asmara"],
    "Somalia": ["Africa/Mogadishu"],
    "Djibouti": ["Africa/Djibouti"],
    "Algeria": ["Africa/Algiers"],
    "Burundi": ["Africa/Bujumbura"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Equatorial Guinea": ["Africa/Malabo"],
    "Swaziland": ["Africa/Mbabane"],
    "Lesotho": ["Africa/Maseru"],
    "Botswana": ["Africa/Gaborone"],
    "Comoros": ["Indian/Comoro"],
    "Cabo Verde": ["Atlantic/Cape_Verde"],
    "Samoa": ["Pacific/Apia"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Tonga": ["Pacific/Tongatapu"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Cook Islands": ["Pacific/Rarotonga"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Palau": ["Pacific/Palau"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Nauru": ["Pacific/Nauru"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tonga": ["Pacific/Tongatapu"],
    "Fiji": ["Pacific/Fiji"],
    "Samoa": ["Pacific/Apia"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Fiji": ["Pacific/Fiji"],
    "Tonga": ["Pacific/Tongatapu"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Fiji": ["Pacific/Fiji"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Malta": ["Europe/Malta"],
    "Cyprus": ["Asia/Nicosia"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Tajikistan": ["Asia/Dushanbe"],
    "Turkmenistan": ["Asia/Ashgabat"],
    "Uzbekistan": ["Asia/Tashkent"],
    "Iran": ["Asia/Tehran"],
    "Iraq": ["Asia/Baghdad"],
    "Afghanistan": ["Asia/Kabul"],
    "Syria": ["Asia/Damascus"],
    "Lebanon": ["Asia/Beirut"],
    "Jordan": ["Asia/Amman"],
    "Israel": ["Asia/Jerusalem"],
    "Palestine": ["Asia/Gaza", "Asia/Hebron"],
    "Qatar": ["Asia/Qatar"],
    "Bahrain": ["Asia/Bahrain"],
    "Kuwait": ["Asia/Kuwait"],
    "Oman": ["Asia/Muscat"],
    "Yemen": ["Asia/Aden"],
    "Sri Lanka": ["Asia/Colombo"],
    "Maldives": ["Indian/Maldives"],
    "Nepal": ["Asia/Kathmandu"],
    "Bhutan": ["Asia/Thimphu"],
    "Myanmar": ["Asia/Yangon"],
    "Laos": ["Asia/Vientiane"],
    "Cambodia": ["Asia/Phnom_Penh"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Brunei": ["Asia/Brunei"],
    "Timor-Leste": ["Asia/Dili"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Samoa": ["Pacific/Apia"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Federated States of Micronesia": ["Pacific/Pohnpei"],
    "Mauritius": ["Indian/Mauritius"],
    "Seychelles": ["Indian/Mahe"],
    "Madagascar": ["Indian/Antananarivo"],
    "Comoros": ["Indian/Comoro"],
    "Malawi": ["Africa/Blantyre"],
    "Zimbabwe": ["Africa/Harare"],
    "Zambia": ["Africa/Lusaka"],
    "Namibia": ["Africa/Windhoek"],
    "Botswana": ["Africa/Gaborone"],
    "Lesotho": ["Africa/Maseru"],
    "Eswatini": ["Africa/Mbabane"],
    "Angola": ["Africa/Luanda"],
    "Mozambique": ["Africa/Maputo"],
    "Tanzania": ["Africa/Dar_es_Salaam"],
    "Uganda": ["Africa/Kampala"],
    "Rwanda": ["Africa/Kigali"],
    "Burundi": ["Africa/Bujumbura"],
    "Democratic Republic of the Congo": ["Africa/Kinshasa", "Africa/Lubumbashi"],
    "Republic of the Congo": ["Africa/Brazzaville"],
    "Cameroon": ["Africa/Douala"],
    "Central African Republic": ["Africa/Bangui"],
    "Chad": ["Africa/Ndjamena"],
    "Niger": ["Africa/Niamey"],
    "Benin": ["Africa/Porto-Novo"],
    "Togo": ["Africa/Lome"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Senegal": ["Africa/Dakar"],
    "Mali": ["Africa/Bamako"],
    "Guinea": ["Africa/Conakry"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Sierra Leone": ["Africa/Freetown"],
    "Liberia": ["Africa/Monrovia"],
    "Ivory Coast": ["Africa/Abidjan"],
    "Mauritania": ["Africa/Nouakchott"],
    "Benin": ["Africa/Porto-Novo"],
    "Eritrea": ["Africa/Asmara"],
    "Somalia": ["Africa/Mogadishu"],
    "Djibouti": ["Africa/Djibouti"],
    "Algeria": ["Africa/Algiers"],
    "Burundi": ["Africa/Bujumbura"],
    "Burkina Faso": ["Africa/Ouagadougou"],
    "Gambia": ["Africa/Banjul"],
    "Guinea-Bissau": ["Africa/Bissau"],
    "Equatorial Guinea": ["Africa/Malabo"],
    "Swaziland": ["Africa/Mbabane"],
    "Lesotho": ["Africa/Maseru"],
    "Botswana": ["Africa/Gaborone"],
    "Comoros": ["Indian/Comoro"],
    "Cabo Verde": ["Atlantic/Cape_Verde"],
    "Samoa": ["Pacific/Apia"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Tonga": ["Pacific/Tongatapu"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Cook Islands": ["Pacific/Rarotonga"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Palau": ["Pacific/Palau"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Nauru": ["Pacific/Nauru"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tonga": ["Pacific/Tongatapu"],
    "Fiji": ["Pacific/Fiji"],
    "Samoa": ["Pacific/Apia"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Fiji": ["Pacific/Fiji"],
    "Tonga": ["Pacific/Tongatapu"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Kiribati": ["Pacific/Tarawa"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Fiji": ["Pacific/Fiji"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Malta": ["Europe/Malta"],
    "Cyprus": ["Asia/Nicosia"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Tajikistan": ["Asia/Dushanbe"],
    "Turkmenistan": ["Asia/Ashgabat"],
    "Uzbekistan": ["Asia/Tashkent"],
    "Iran": ["Asia/Tehran"],
    "Iraq": ["Asia/Baghdad"],
    "Afghanistan": ["Asia/Kabul"],
    "Syria": ["Asia/Damascus"],
    "Lebanon": ["Asia/Beirut"],
    "Jordan": ["Asia/Amman"],
    "Israel": ["Asia/Jerusalem"],
    "Palestine": ["Asia/Gaza", "Asia/Hebron"],
    "Qatar": ["Asia/Qatar"],
    "Bahrain": ["Asia/Bahrain"],
    "Kuwait": ["Asia/Kuwait"],
    "Oman": ["Asia/Muscat"],
    "Yemen": ["Asia/Aden"],
    "Sri Lanka": ["Asia/Colombo"],
    "Maldives": ["Indian/Maldives"],
    "Nepal": ["Asia/Kathmandu"],
    "Bhutan": ["Asia/Thimphu"],
    "Myanmar": ["Asia/Yangon"],
    "Laos": ["Asia/Vientiane"],
    "Cambodia": ["Asia/Phnom_Penh"],
    "Mongolia": ["Asia/Ulaanbaatar"],
    "Brunei": ["Asia/Brunei"],
    "Timor-Leste": ["Asia/Dili"],
    "Vanuatu": ["Pacific/Port_Vila"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Samoa": ["Pacific/Apia"],
    "Tonga": ["Pacific/Tongatapu"],
    "Kiribati": ["Pacific/Tarawa"],
    "Tuvalu": ["Pacific/Funafuti"],
    "Nauru": ["Pacific/Nauru"],
    "Marshall Islands": ["Pacific/Majuro"],
    "Palau": ["Pacific/Palau"],
    "Micronesia": ["Pacific/Pohnpei"],
    "Federated States of Micronesia": ["Pacific/Pohnpei"],
    "Mauritius": ["Indian/Mauritius"],
    "Seychelles": ["Indian/Mahe"],
    "Madagascar": ["Indian/Antananarivo"],
    "Comoros": ["Indian/Comoro"],
    "Malawi": ["Africa/Blantyre"],
    "Zimbabwe": ["Africa/Harare"],
    "Zambia": ["Africa/Lusaka"],
    "Namibia": ["Africa/Windhoek"],
    "Botswana": ["Africa/Gaborone"],
    "Lesotho": ["Africa/Maseru"],
    "Eswatini": ["Africa/Mbabane"],
    "Angola": ["Africa/Luanda"],
    "Mozambique": ["Africa/Maputo"],
    "Tanzania": ["Africa/Dar_es_Salaam"],
    "Uganda": ["Africa/Kampala"],
    "Rwanda": ["Africa/Kigali"],
    "Burundi": ["Africa/Bujumbura"],
    "Democratic Republic of the Congo": ["Africa/Kinshasa", "Africa/Lubumbashi"],
    "Republic of the Congo": ["Africa/Brazzaville"],
    "Cameroon": ["Africa/Douala"],
    "Central African Republic": ["Africa/Bangui"],
    "Chad": ["Africa/Ndjamena"],
    "Niger": ["Africa/Niamey"]
}

# Function to convert text to speech
def speak(text):
    """Converts text to speech."""
    engine = pyttsx3.init()
    engine.say(text)
    engine.runAndWait()

# Function to get the current time in a specific timezone
def get_time_in_timezone(timezone_name):
    timezone = pytz.timezone(timezone_name)
    current_time = datetime.now(timezone).strftime("%H:%M")
    return current_time

# Function to get and publish the time in a given country's timezones
def get_country_time(country, client):
    timezones = country_timezones.get(country, [])
    if not timezones:
        print(f"Invalid country: {country}")
        return

    print(f"Time in {country}:")
    for tz_name in timezones:
        current_time = get_time_in_timezone(tz_name)
        print(f"{tz_name}: {current_time}")
        speak(f"{tz_name}: {current_time}")

        # Publish the message to MQTT broker
        client.publish(MQTT_TOPIC, f"{country} - {current_time}")
# Callback function when connecting to MQTT broker
def on_connect(client, userdata, flags, rc):
    print("Connected to MQTT broker with code", rc)

def main():
    speak("welcome to the world clock. here you can know the time for any country , just say the name of the country.")
    client = mqtt.Client()
    client.on_connect = on_connect

    client.connect(MQTT_BROKER_HOST, MQTT_BROKER_PORT, 60)

    recognizer = sr.Recognizer()

    while True:
        with sr.Microphone() as source:
            print("Speak the country name (or say 'exit' to quit):")
            audio = recognizer.listen(source)

        try:
            country = recognizer.recognize_google(audio).strip().title()
            print(f"You said: {country}")

            if country == 'Exit':
                break

            get_country_time(country, client)
        except sr.UnknownValueError:
            print("Sorry, I didn't catch that. Please try again.")
        except sr.RequestError:
            print("Speech recognition service unavailable. Please check your internet connection.")


if __name__ == "__main__":
    main()
